[package]
name = "aurora_concurrency"
version = "0.1.0"
edition = "2021"

[dependencies]
aurora_types = { path = "../aurora_types" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
