[package]
name = "aurora_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
aurora_air = { path = "../aurora_air" }
aurora_mir = { path = "../aurora_mir" }
aurora_types = { path = "../aurora_types" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[dev-dependencies]
