[package]
name = "aurora_diagnostics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
aurora_effects = { path = "../aurora_effects" }
serde.workspace = true
serde_json.workspace = true
tower-lsp = "0.20"
