[package]
name = "aurora_air"
version = "0.1.0"
edition = "2021"

[dependencies]
aurora_mir = { path = "../aurora_mir" }
aurora_types = { path = "../aurora_types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"

[dev-dependencies]
