[package]
name = "aurora_air"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
aurora_mir = { path = "../aurora_mir" }
serde.workspace = true
serde_json.workspace = true
