[package]
name = "aurora_testing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
proptest = "1.4"
serde = { workspace = true }
thiserror = { workspace = true }
